services:
  backend:
    build: ./backend
    develop:
      watch:
        - action: restart
          path: ./backend/Dockerfile

  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - "3002:3000"
    develop:
      watch:
        - action: rebuild
          path: ./frontend/trigger.txt
