services:
  backend:
    build: ./backend

  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - "3002:3000"
    develop:
      watch:
        - action: rebuild
          path: ./frontend
          include:
            - trigger.txt
            - Dockerfile
            - Caddyfile
